### ISSUE TITLE
[Item 2] 자바빈즈 패턴에서 일관성이 무너지는 이유

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#1]
> 16pg, 객체 하나를 만들려면 메서드를 여러 개 호출해야 하고, 객체가 완전히 생성되기 전까지는 일관성(consistency)이 무너진 상태에 놓이게 된다.
## 질문 내용
자바빈즈 패턴에서, 일관성이 깨진다고 설명하고 있는데 어떤 점에서 일관성이 무너지는지 잘 이해가 되지 않음

**Comment by ehBeak** [comment]
생성자 호출로 객체를 생성해도 setter를 사용하기 전까지는 완성된 객체가 아니라는 뜻

```
Student student = new Student("이진혁", 19, "3417");
student.setHomeAddress("경남 김해시");
student.setPhoneNumber("010-1111-1111");
```

`setHomeAddress` 함수를 실행하기 전까지는 완성된 객체가 아니다
