### ISSUE TITLE
[item 47] 스트림 사용 API에서 반복을 지원할 때 프로그래머가 감수해야하는 것

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#100]
> 285pg, 이는 스트림만 반환하는 API가 반환한 값을 for-each로 반복하길 원하는 프로그래머가 감수해야할 부분이다.
## 질문 내용
어떤 부분을 감수해야하는 것인지 잘 모르겠다.

**Comment by ehBeak** [comment]
file.lines는 반복자를 사용하는 것이 더 좋다. 하지만, 만약 API가 스트림을 반환한다면 반복자 사용이 불가하기 때문에 사용하는 사람이 이를 감수해야 한다.
