### ISSUE TITLE
[item 48] 메르센소수를 병렬 작업할 경우, 숫자가 커질수록 걸리는 시간이 2배씩 더 걸리는 이유

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#102]
> 292pg, 따라서 21, 22, 23번째 메르센 소수를 찾는 작업이 병렬로 시작되는데, 20번째 계산이 끝나더라도 이 계산들은 끝나지 않는다. 각각 20번째 계산보다 2배, 4배, 8배의 시간이 더 필요하기 때문이다.
## 질문 내용
숫자가 커지므로 메르센 소수를 작업이 더 오래 걸린다는 것은 알겠는데, 왜 2배, 4배, 8배씩 커지는지 잘 모르겠다.

**Comment by ehBeak** [comment]
메르센 소수 알고리즘
https://jeonggyun.tistory.com/139
