### ISSUE TITLE
[item 49] 실패 원자성의 의미

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#103]
> 298pg, 다시 말해 매개변수 검사에 실패하면 실패 원자성을 어기는 결과를 낳을 수 있다.
## 질문 내용
실패 원자성이란 무엇인지 궁금하다.

**Comment by ehBeak** [comment]
'만약 어떤 메서드가 인스턴스를 변경하려고 했을 떄, 호출된 메서드가 실패하더라도 해당 객체는 메서드 호출 전 상태를 유지해야한다.'라는 의미이다.
