### ISSUE TITLE
[item50] 접근자에서는 clone을 사용해도 되는 이유

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#104]
> pg, 305 생성자와 달리 접근자 메서드에서는 방어적 복사에 clone을 사용해도 된다. Period가 가지고 있는 Date 객체는 java.util.Date임이 확실하기 때문이다.
## 질문 내용
위에서 말하는 내용이 잘 이해가 안간다.

**Comment by seonjuleee** [comment]
```java
class NewDate extends Date {
        @Override
        public Object clone() {
            System.out.println("clone!!!!");
            return super.clone();
        }
    }
```
간단하게 Date의 하위 클래스인 NewDate 클래스가 있다고 해보자. 이 클래스는 악의적인 클래스라고 가정하자.
접근자 메서드인 `getEnd()`에 clone을 이용하여 방어적 복사를 한다면 다음과 같이 나타낼 수 있다.
```java
public Date end() {
       return (Date) end.clone();
}
```
여기서 반환되는 end는 Date 객체임이 확실해지므로 수정 가능성이 없다.
그렇기 때문에 접근자 메서드에서는 clone 메서드를 이용하여 방어적 복사를 하는 것이 가능하다.
