### ISSUE TITLE
[item 50] 유효성 검사를 하기 전에 방어적 복사본을 만든 이유

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#105]
> pg,304 멀티스레딩 환경이라면 원본 객체의 유효성을 검사한 후 복사본을 만드는 그 찰나의 취약한 순간에 다른 스레드가 원본 객체를 수정할 위험이 있기 때문이다.
## 질문 내용
멀티스레딩 환경에서 다른 스레드가 원본 객체를 수정하는 경우의 예를 코드로 보고 싶다. 또는 예시가 궁금하다.

**Comment by seonjuleee** [comment]
유효성 검사를 하기 전에 방어적 복사본을 만든 이유는, 복사본을 만들기 전 유효성 검사를 하면서 객체의 값이 수정될 수도 있기 때문이다.
