### ISSUE TITLE
메소드에 호출에 빌더 패턴을 응용하는 방법

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#106]
> pg310 먼저, 모든 매개변수를 하나로 추상화한 객체를 정의하고, 클라이언트에서 이 객체의 세터 메서드를 호출해 ~~ 마지막으로, 설정이 완료된 객체를 넘겨 원하는 계산을 수행한다.

## 질문 내용
위에서 말한 방식이 이해가 안감.
예시 궁금함

**Comment by seonjuleee** [comment]
원래의 코드
```java
public void notUseBuilder(String name, String phoneNumber, String address) {
    ...
}
```
빌더 패턴 사용
```java
public void useBuilder(Member member) {
    ...
}
```

```java
// Client 코드
Member member = Member.build()
                .setName("홍길동")
                .setAddress("서울시 노원구")
                .build();
useBuilder(member);
```

빌더 패턴을 사용하면 setter메서드(setName, setAddress)로 여러 메서드를 쪼개고, 여러 매개변수를 묶어주는 도우미 클래스를 만들어 메서드에 들어가는 매개변수의 수를 줄일 수 있다.

이때 각 세터메서드는 매개변수를 한 개 혹은 연관된 매개변수만 설정하도록 하고, 클라이언트에서는 매개변수를 설정한 후 유효성 검사를 해야한다.
