### ISSUE TITLE
[item 52] 다중정의에서의 관련 없는 클래스의 의미

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#107]
> 318pg, 한편, String과 Throwable처럼 상위/하위 관계가 아닌 두 클래스는 '관련 없다(unrelated)'고 한다. 그리고 어떤 객체도 관련 없는 두 클래스의 공통 인스턴스가 될 수 없으므로, 관련 없는 클래스끼리도 근본적으로 다르다.
## 질문 내용
이 내용이 
1. 상위/하위 관계가 아닌 클래스는 관련이 없으므로, 다중정의를 해도 괜찮다는 의미인지, 
2. 서로 다른 함수형 인터페이스라도 같은 위치의 인수로 받아서는 안되니 다중정의를 하면 안된다는 의미인지

정확하게 어떤 의미를 갖는 것인지 모르겠다.

**Comment by ehBeak** [comment]
예제에서 list, set은 collection와 상위/하위 관계이기 때문에, 예시에서 보여준 것 처럼 다중정의를 하면 예상하지 못한 방식으로 흘러갈 수 있다. 그러나 string과 throwable은 상위/하위 관계가 아니라서 애초에 위의 예제처럼 코드를 짠다면 컴파일 오류가 난다.
