### ISSUE TITLE
[item63]

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#113]
> 363 pg, 이 방식의 문제는 스레드 구분용 문자열 키가 전역 이름공간에서 공유된다는 점이다.
## 질문 내용
이 부분이 왜 어떤 문제가 되는지 모르겠음. 만약 지역변수가 된다면 무엇을 개선할 수 있는지 모르겠음

**Comment by seonjuleee** [comment]
스레드를 구분하는 키가 전역 이름공간에서 공유되는데, 이 때 그 키를 구성하는 것이 문자열이므로 쉽게 키를 사용할 수 있다. 그러면 키에 해당하는 변수도 접근이 가능해지기 때문에 위조가 가능해져 보안에 취약해진다.
