### ISSUE TITLE
[item 81] wait 메서드를 대기 반복문(wait loop) 안에 사용해야 하는 이유

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#119]
> 435pg, wait 메서드를 사용할 때는 반드시 대기 반복문(wait loop) 관용구를 사용하라. 반복문 밖에서는 절대로 호출하지 말자.
## 질문 내용
반복문 밖에서 호출하면 안되는 이유가 궁금하다.

**Comment by ehBeak** [comment]
반복을 사용하지 않는 다면, 스레드가 대기 풀에 들어가고 notify에 의해 대기 풀에서 나오고 다시 스레드를 실행한다. 그러나 그 실행된 스레드는 아직 조건에 충족되지 않은 스레드 일 수 있다. 그렇기 때문에 반복문을 사용해서 계속적으로 조건에 만족하는 지 체크를 하는 것이다.

참고: [[이펙티브 자바 3판] 아이템 81. wait와 notify보다는 동시성 유틸리티를 애용하라](https://madplay.github.io/post/prefer-concurrency-utilities-to-wait-and-notify),
      [condition(wait, notify[All] ) : Java 쓰레드 동기화(Synchronization)](https://jamssoft.tistory.com/200)
