### ISSUE TITLE
[item7] 다 쓴 참조를 해제하는 가장 좋은 방법

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#12]
> pg.38 다 쓴 참조를 해제하는 가장 좋은 방법은 그 참조를 담은 변수를 유효 범위 밖으로 밀어내는 것이다.
## 질문 내용
다 쓴 참조를 해제하는 방법중 null처리를 하는 방법을 말하는 건가?

**Comment by seonjuleee** [comment]
참조를 해제하는 방법에 null 처리를 하는 것으로 설명했기 때문에 null 처리를 하는 방법을 말하는 것으로 볼 수 있다.
