### ISSUE TITLE
[item 8] finalizer 공격의 예시

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#16]
> 42pg, finalizer 공격 원리는 간단하다. 생성자나 직렬화 과정에서 예외가 발생하면, 이 생성되다 만 객체에서 악의적인 하위 클래스의 finalizer가 수행될 수 있게 된다.
## 질문 내용
finalizer 공격에 대한 설명만으로는 이해가 잘 가지 않아서 이에 대한 예시가 궁금함

**Comment by ehBeak** [comment]
어떤 악의적인 A클래스가 B클래스를 상속하면, A클래스는 B(부모)클래스의 finalizer메소드를 오버라이딩 할 수 있다.
그리고 이 A클래스가 생성될 때 예외가 발생하면, finalizer에 의해서 예외가 터지지 않고 결국 A객체는 좀비 클래스가 된다.
이렇게 되면 A객체는 오버라이딩한 finalizer메소드를 통해 B클래스에 마음대로 접근이 가능하게 된다.
이를 막기 위해서는 B클래스를 상속받지 못하도록 final로 선언을 하거나 B클래스에서 finalizer메소드를 final선언하여 오버라이딩 못하게 해야한다.

**Comment by ehBeak** [comment]
https://www.youtube.com/watch?v=6kNzL1bl1kI
