### ISSUE TITLE
[item10] 추이성 위배시, 무한 재귀

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#17]
> pg.58 또한 이 방식은 무한 재귀에 빠질 위험도 있다. Point의 또 다른 하위 클래스로 SmellPoint를 만들고, equals는 같은 방식으로 구현했다고 해보자. 그런 다음 myColorPoint.equals(mySmellPoint)를 호출하면 StackOverFlowError를 일으킨다.
## 질문 내용
두 개의 자식 클래스를 만들고 equals를 호출하면 재귀에 빠지게 되는 예시

**Comment by seonjuleee** [comment]
ColorPoint의 equals
```java
@Override public boolean equals(Object o) {
    if (!(o instanceof Point)) return false;
    
    // o가 일반 Point면 색상을 무시하고 비교
    if (!(o instanceof ColorPoint)) return o.equals(this);
    
    // o가 ColorPoint면 색상까지 비교
    return super.equals(o) && ((ColorPoint) o).color == color;
}
```

SmellPoint의 equals
```java
@Override public boolean equals(Object o) {
    if (!(o instanceof Point)) return false;

    // o가 일반 Point면 색상을 무시하고 비교
    if (!(o instanceof SmellPoint)) return o.equals(this);

    // o가 ColorPoint면 색상까지 비교
    return super.equals(o) && ((SmellPoint) o).color == color;
}
```
`myColorPoint.equals(mySmellPoint)`를 호출하면
1. ColorPoint의 equals에서 객체가 SmellPoint이므로 SmellPoint의 equals를 호출
2. SmellPoint의 equals에서 객체가 ColorPoint이므로 ColorPoint의 equals를 호출
3.  ...

1번과 2번이 계속 반복되며 무한 재귀가 일어나게 되고, 결국 StackOverFlowError가 발생한다.
