### ISSUE TITLE
[Item 11] 지연 초기화 시 클래스 스레드 안정성을 고려해야하는 이유

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#18]
> 71pg, 필드를 지연 초기화하려면 그 클래스를 스레드 안전하게 만들도록 신경 써야 한다.
## 질문 내용
필드를 지연 초기화하려면 스레드를 안전하게 만들어야 하는 이유가 궁금함

**Comment by ehBeak** [comment]
필드를 지연 초기화하면, 어떤 스레드가hashCode()를 호출할 때 hashCode가 지연 초기화 된다. 
그런데 만약 스레드 A가 hashCode()를 호출해서 hashCode를 계산하고 있는 와중에 
스레드 B가 hashCode()에 접근을 한다면 계산에 문제가 생긴다.
때문에 hashCode()를 한 스레드가 접근하고 있다면 다른 쓰레드는 접근하지 못하도록 해야한다. 
그것을 '스레드에 안전하다'라고 한다.
