### ISSUE TITLE
[item11] 모든 객체에서 똑같은 해시코드를 반환하는 경우

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#19]
> pg.68 모든 객체에게 똑같은 값만 내어주므로 모든 객체가 해시테이블의 버킷 하나에 담겨 마치 연결 리스트(linked list)처럼 동작한다. 그 결과 평균 수행 시간이 O(1)인 해시테이블이 O(n)으로 느려져서, 객체가 많아지면 도저히 쓸 수 없게 된다.
## 질문 내용
연결 리스트처럼 동작한다는 의미가 이해가 안감
연결 리스트처럼 동작하게 되면, 수행 시간에 변화가 생기는 이유 모르겠음

**Comment by seonjuleee** [comment]
![hashcode](https://user-images.githubusercontent.com/52817735/154258373-3a9cfd3f-f7f0-47b6-8c78-1d07b1a0763b.png)

해시테이블은 다음과 같이 구성되어 있어서 
모든 객체의 해시코드가 같은 값이게 될 경우, 버킷 하나에 다 담겨서 연결 리스트처럼 표현이 될 수 밖에 없다.
