### ISSUE TITLE
[item11] 해시코드를 계산하기 보다는 캐싱 방법 고려

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#20]
> pg.71 클래스가 불변이고 해시코드를 계산하는 비용이 크다면, 매번 새로 계산하기 보다는 캐싱하는 방식을 고려해야 한다.
## 질문 내용
캐싱 하는 방법 예시나 설명

**Comment by seonjuleee** [comment]
클래스가 변하지 않고 해시코드 계산 비용이 크다면 해시코드를 사용할 때마다 매번 계산하는 것보단 캐시 안에 저장하는 방식을 얘기하는 것 같다.
