### ISSUE TITLE
[Item 13] 배열을 가진 필드를 clone할 경우 문제점

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#21]
> 80pg, 원본이나 복제본 중 하나를 수정하면 다른 하나도 수정되어 불변식을 해친다는 이야기다.
## 질문 내용
이 부분이 어떤 것을 이야기하는지 이해가 되지 않음.

**Comment by ehBeak** [comment]
배열 필드를 가진 클래스를 clone하게 되면, 
배열의 참조값 즉, 주소값이 복사가 되어(얕은 복사) 복사된 배열 필드도 원본의 배열을 참조하게 된다. 
예를 들어, 만약 A 인스턴스를 clone하여 B인스턴스를 생성했다면, B의 배열 필드는 A의 배열을 가리키게 된다는 것이다. 
이 상태에서 B의 배열 필드를 참조하여 배열의 내용을 수정하면 A필드가 참조하는 배열도 바뀌게 된다. 
이 의미가 불변식을 해친다는 이야기다.
