### ISSUE TITLE
[item 15] public클래스의 필드가 public이고 가변 객체를 참조할 때

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#24]
> pg.99 필드가 가변 객체를 참조하거나, final이 아닌 인스턴스 필드를 public으로 선언하면, 그 필드에 담을 수 있는 값을 제한할 힘을 잃게 된다. 그 필드와 관련된 모든 것은 불변식을 보장할 수 없게 된다는 뜻이다. 여기에 더해, 필드가 수정될 때 (락 획득 같은) 다른 작업을 할 수 없게 되므로 public 가변 필드를 갖는 클래스는 일잔적으로 스레드 안전하지 않다.
## 질문 내용
문맥 이해

**Comment by seonjuleee** [comment]
가변객체이므로 값이 변경될 수 있는데, 이게 public이면 하나에서 변경해도 다른 것도 함께 변경되기 때문에 불변식을 보장할 수 없다.
