### ISSUE TITLE
[item 15] 모듈 시스템에서의 접근 권한

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#27]
> 101pg, 즉, 모듈이 공개했는지 여부와 상관없이, public 클래스가 선언한 모든 public 혹은 protected 멤버를 모듈 밖에서도 접근할 수 있게 된다. 새로 등장한 이 접근 수준을 적극 활용한 대표적인 예가 바로 JDK 자체이다. 자바 라이브러리에서 공개하지 않은 패키지들은 해당 모듈 밖에서는 절대로 접근할 수 없다.
## 질문 내용
jar파일을 모듈 경로가 아닌 classpath에 두면 접근 권한이 선언한 접근 권한과 달리 모두에게 공개된다는 의미가 맞는지?

**Comment by ehBeak** [comment]
classpath에 두면, pubulic 클래스에서 선언한 public, protected 멤버들은 모듈 밖에서도 공게가 된다는 의미이다.
