### ISSUE TITLE
[item 18] 잘못된 상속의 예시 이해

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#29]
> 115pg, InstrumentedHashSet의 addAll은 addCount에 3을 더한 후 HashSet의 addAll 구현을 호출했다. HashSet의 addAll은 각 원소를 add 메서드를 호출해 추가하는데, 이때 불리는 add는 InstrumentedHashSet에서 재정의한 메서드다. 따라서 addCount에 값이 중복해서 더해져, 최종값이 6으로 늘어난 것이다.
## 질문 내용
이 문장 내용이 헷갈림
InstrumentedHashSet의 addAll이 실행될 때, 
```java
@Override
public boolean addAll(Collection<? extends E> c) {
    addCount += c.size();
    return super.addAll(c);
}
```
여기서 addCount가 3이 되고,
HashSet의 addAll이 add가 사용되기 때문에
```java
@Override
public boolean add(E e) {
    addCount++;
    return super.add(e);
}
```
이 과정에서 addCount가 6이 되는 것이 맞는지 궁금함

**Comment by ehBeak** [comment]
InstrumentedHashSet의 addAll함수가 실행되면, super.addAll(c)함수가 실행된다. 
상위 클래스의 addAll 함수는 다음과 같다. (HashSet이 extends한 AbstactCollection의 addAll())
```java
public boolean addAll(Collection<? extends E> c) {
        boolean modified = false;
        Iterator var3 = c.iterator();

        while(var3.hasNext()) {
            E e = var3.next();
            if (this.add(e)) {
                modified = true;
            }
        }

        return modified;
    }
```
이 함수를 실행하는 과정에서 add()함수가 호출이 되는데, 
InstrumentedHashSet이 HashSet을 상속했기 때문에 가장 하위타입의 오버라이딩 된 메소드인 InstrumentedHashSet의 add() 함수가 호출이 된다. 
여기서 add() 함수는 addCount를 1씩 증가 시킨다. 때문에 원소 1개를 추가할 때마다 값이 2 증가되어 3개를 추가하면 6이 되는 것이다.
