### ISSUE TITLE
[item1] 인터페이스를 반환하는 정적 메서드가 필요할 때

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#30]
> pg10. 그렇기 때문에 이름이 Type인 인터페이스를 반환하는 정적 메서드가 필요하면, "Types"라는 (인스턴스화 불가인)동반 클래스를 만들어 그 안에 정의하는 것이 관례였다.
## 질문 내용
동반 클래스 개념과 위에서 말하는 것 예시

**Comment by seonjuleee** [comment]
동반 클래스는 다단계 연산을 기본으로 제공하는 클래스 (ex. String, StringBuffer)
