### ISSUE TITLE
[item18] 컴포지션을 사용한 클래스의 동작 방식

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#31]
> pg.118 구체적으로는 Set인터페이스를 구현했고, Set의 인스턴스를 Set으로 받는 생성자를 하나 제공한다. 임의의 Set에 계측 기능을 덧씌워 새로운 Set으로 만드는 것이 이 클래스의 핵심이다.
## 질문 내용
코드 18-2와 코드 18-3가 addAll()을 호출할 때 정확한 방식으로 동작하는지 모르겠음

**Comment by seonjuleee** [comment]
18-2는 add를 불러올 때 그 하위타입인 InstrumentedHashSet의 add를 불러왔지만, 18-3은 InstrumentedHashSet의 add가 아닌 AbstractCollection의 add를 불러옴
