### ISSUE TITLE
[item 18] 래퍼 클래스는 콜랙 프레임워크와 어울리지 않다.

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#32]
> pg.119 콜백 프레임워크에서 자기 자신의 참조를 다른 객체에 넘겨서 다음 호출(콜백) 때 사용하도록 한다. 내부 객체는 자신을 감싸고 있는 래퍼의 존재를 모르니 대신 자신(this)의 참조를 넘기고, 콜백 때는 레퍼가 아닌 내부 객체를 호출하게 된다. 이를 SELF문제라고 한다.
## 질문 내용
예제 필요

**Comment by seonjuleee** [comment]
콜백 프레임워크는 자기 자신을 리턴하도록 해야하는데, 래퍼 클래스를 사용하게 되면 자기 자신을 리턴하는 것이 아닌 내부 객체를 리턴하므로 콜백 프레임워크와 어울리지 않다고 하는 것
