### ISSUE TITLE
[item 20] equals와 hashCode를 디폴트 메서드로 제공해서는 안되는 이유

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#34]
> 132pg, 많은 인터페이스가 equals와 hashCode 같은 Object의 메서드를 정의하고 있지만, 이들은 디폴트 메서드로 제공해서는 안 된다.
## 질문 내용
디폴트 메서드가 무엇이고, equals와 hashCode는 디폴트 메서드로 제공하면 안되는 이유가 궁금함

**Comment by ehBeak** [comment]
디폴트 메서드란 인터페이스의 함수 중에, 추상함수가 아닌 구현부가 존재하는 메서드이다.

**Comment by ehBeak** [comment]
eqauls와 hashcode는 두 인스턴스가 동일한가를 판단한다. 
인터페이스는 인스턴스를 참조변수로는 사용할 수 있지만, 인스턴스를 생성할 수는 없다.
인터페이스에서 디폴트 메서드를 사용해서 equals와 hashcode를 구현할 수 있게 되었지만, 
인터페이스는 인스턴스 자체를 가질 수 없기 때문에 equals와 hashcode를 구현하면 안된다.
