### ISSUE TITLE
[item24] 톱레벨 클래스란?

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#42]
> 146pg, 중첩 클래스는 자신을 감싼 바깥 클래스에서만 쓰여야 하며, 그 외의 쓰임새가 있다면 톱레벨 클래스로 만들어야 한다.
## 질문 내용
톱레벨 클래스가 무엇인지 궁금함

**Comment by ehBeak** [comment]
톱 레벨 클래스는 중첩 클래스가 아닌 클래스이다.
