### ISSUE TITLE
[item 26] 비한정적 와일드카드 타입의 사용

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#48]
> 158pg, 반면, Collection<?>에는 (null 외에는) 어떤 원소도 넣을 수 없다.
## 질문 내용
어떤 값이든 들어갈 수 있는 것으로 알고 있었는데 null을 제외하고 어떤 원소도 들어갈 수 없다는게 이해가 잘 가지 않음

**Comment by ehBeak** [comment]
위와 같이 null을 제외한 어떤 원소를 넣으려 하면, 컴파일 오류가 발생한다.
```java

    private final ArrayList<?> collection = new ArrayList<>();


    public void add(Object o) {
        collection.add(Integer.valueOf(22)); // 컴파일 오류
        collection.add(null); // null 허용
    }
```

비한정적 와일드 카드로 컬렉션을 선언하면 (ex. ArrayList<?>, Collection<?>) 다음과 같은 규칙을 가진다.
1. null 이외에 어떤 원소도 넣을 수 없다
2. 컬렉션의 엔트리를 조회할 때는 Object 타입으로만 조회가 가능하다.

위와 같은 제약을 해결하려면,
1. 제네릭 메서드를 사용한다.
2. 한정적 와일드 카드를 사용한다.
