### ISSUE TITLE
[item26] 로 타입의 동작방식

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#49]
> pg,154 로 타입은 타입선언에서 제네릭 타입 정보가 전부 지워진 것처럼 동작하는데, 제네릭이 도래하기 전 코드와 호환되도록 하기 위한 궁여지책이라 할 수 있다.

## 질문 내용
로 티입이 어떤 방식으로 동작하는지 정확히 모르겠음.

**Comment by seonjuleee** [comment]
비한정적 와일드카드는 제네릭 타입이 정해지지 않은 채로 동작할 수 있도록 했는데,
로 타입은 제네릭 타입 정보를 지운 것처럼 생각하고 동작한다는 의미인 것 같다.
