### ISSUE TITLE
[item28] 제네릭 배열 허용시 발생할 수 있는 문제 예시

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#50]
> 165pg, 제네릭 배열을 생성하는 (1)이 허용된다고 가정해보자. ~ 컴파일러는 꺼낸 원소를 자동으로 String으로 형변환하는데, 이 원소는 Integer이므로 런타임에 ClassCastException이 발생한다.
## 질문 내용
책에 있는 예시 부분이 잘 이해가 가지 않음
```java
List<String>[] stringLists = new List<String>[1];
List<Integer> intList = List.of(42);
Object[] objects = stringLists;
objects[0] = intList;
String s = stringLists[0].get(0);
```

**Comment by ehBeak** [comment]
```java
List<String>[] stringLists = new List<String>[1]; // ...(1)
List<Integer> intList = List.of(42); // ...(2)
Object[] objects = stringLists; // ...(3)
objects[0] = intList; // ...(4)
String s = stringLists[0].get(0); // ...(5)
```

(1) List<String>[] 타입은 선언 불가이지만, 가능하다고 가정한다.(문제의 시작)
(2) List<Integer>을 선언하고 42의 크기가 1개인 리스트를 참조시킨다.
(3) Object 배열을 (1)에서 선언한 stringLists로 초기화 시킨다. 
     배열은 공변 변환이 가능하고 Object는 List<String>의 부모이기 때문에 Object[]는 List<String>[]을 참조할 수 있다.
(4) Object[0]은 Object타입이고 intList는 List<Integer>타입으로, Object의 자식 타입이기 때문에 참조 가능하다. 여기서 Object[]가 List<String>[]을 참조했기 때문에, Object[0]=intList는 stringLists[0]에 intList를 넣은 것과 같다. 하지만 컴파일 시점에 문제가 없으며, 런타임 시점에도 제네릭 소거로 문제가 없다.
(5) 값을 조회할 때는 제네릭으로 선언한 리스트의 경우 설정한 타입으로 형변환하기 때문에 stringList의 값을 꺼낼때는 List<String>으로 형변환한다. 하지만 넣은 값은 List<Integer>이기 때문에 조회 과정에서 ClassCastException이 발생한다.
