### ISSUE TITLE
[item28] 제네릭 타입의 불공변

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#51]
> pg ,163 반면, 제네릭은 불공변이다. 즉, 서로 다른 타입 Type1과 Type2가 있을 때, List<Type1>은 List<Type2>의 하위 타입도 아니고 상위 타입도 아니다.
## 질문 내용
만약 Sub가 Super의 하위 타입이라면 제네릭인 List<Sub>는 List<Super>의 하위타입이 아니라는 것을 이야기하는지 헷갈림

**Comment by seonjuleee** [comment]
Type1, Type2 서로 다른 타입 두개가 있을 때, List<Type1>과 List<Type2>는 하위 타입도, 상위 타입도 아니라는 뜻
