### ISSUE TITLE
[item30] 재귀적 타입 한정

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#56]
> 178pg, 자기 자신이 들어간 표현식을 사용하여 타입 매개변수의 허용 범위를 한정할 수 있다. 바로 재귀적 한정이라는 개념이다.
## 질문 내용
재귀적 타입 한정의 개념과 예시가 이해안감

**Comment by seonjuleee** [comment]
**재귀적 타입 한정**은 타입 매개변수의 허용 범위를 한정할 때 자기 자신이 들어간 표현식을 사용하는 것.

예시로 `Comparable<T>`의 경우 비교하는 것이기 때문에 거의 모든 타입이 자신과 같은 타입의 원소와 비교가 가능하다. (`String`은 `String`끼리 비교하므로 `Comparable<String>을 구현)

그런데 메서드를 사용할 때 그 원소들을 정렬, 검색, 최솟값, 최댓값을 구하는 식으로 사용이 되기 때문에
이 기능을 수행하기 위해 컬렉션에 담긴 모든 원소가 상호 비교될 수 있어야 한다.
그래서 재귀적 타입 한정인 `<E extends Comparable<E>>`을 사용하여 자기 자신과 비교가 가능한 원소들이 들어갈 수 있도록 표현하는 것이다.

```java
static <E extends Comparable<E>> E max(Collection<E> c) {
if (c.isEmpty()) throw new IllegalArgumentException("Collection empty");

E result = null;
for (E e : c) {
    if (result == null || e.compareTo(result) > 0)
        result = Objects.requireNonNull(e);
}
return result;
}
```
