### ISSUE TITLE
[item 31] 펙스 공식 사용방법

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#58]
> 184pg, 이 생성자로 넘겨지는 choices 컬렉션은 T타입의 값을 생산하기만 하니, T를 확장하는 와일드카드 타입을 사용해 선언해야 한다.
## 질문 내용
왜 생산이 되는 것인지 이해가 잘 되지 않는다

**Comment by ehBeak** [comment]
```java
public class Chooser<T> {

    private final List<T> choiceList;

    public Chooser(Collection<? extends T> choices) {
        this.choiceList = new ArrayList<>(choices);
    }

    public T choose() {
        Random rnd = ThreadLocalRandom.current();
        return choiceList.get(rnd.nextInt(choiceList.size()));
    }
}
```

Chooser은 이 클래스의 생성자로, choices라는 매개변수를 받아서 choiceList에 값을 초기화 시켜준다.
즉 choices라는 매개변수는 Chooser 클래스의 필드인 choiceList에 값을 넣어주어 '생산'한다.
때문에 생산자의 choices매개변수는 이 클래스의 생산자 역할을 한다.
