### ISSUE TITLE
[item 31] 목표 타이핑의 개념

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#59]
> 186pg, 목표 타이핑은 자바 8부터 지원하기 시작했는데, 그 전 버전에서도 이런 문제가 흔하진 않았다.
## 질문 내용
목표 타이핑의 개념이 궁금함

**Comment by ehBeak** [comment]
목표 타이핑이란 컴파일러가 자동 형변환을 하여 연산을 수행하는 것을 이야기한다.
자바 8이후에 목표 타이핑 개념이 생기면서 생성자의 <>연산자에 타입을 명시할 필요가 없어졌고 람다도 사용가능해졌다.

참고

https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html#target-typing

https://blog.naver.com/PostView.nhn?blogId=piyoro&logNo=221780773529&redirect=Dlog&widgetTypeCall=true&directAccess=false
