### ISSUE TITLE
[item3] 리플렉션 개념 

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#6]
> pg, 심지어 아주 복잡한 직렬화 상황이나 리플렉션 공격에도 제2의 인스턴스가 생기는 일을 완벽히 막아준다.
## 질문 내용
리플렉션 개념 요구

**Comment by seonjuleee** [comment]
구체적인 클래스 타입을 알지 못해도 그 클래스의 메소드, 타입, 변수들에 접근할 수 있도록 해주는 자바 API
