### ISSUE TITLE
[item31] 한정적 와일드 카드를 사용해 구현한 max함수

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#61]
> 187 pg, 그 근거로, 다음 리스트는 오직 수정된 max로만 처리할 수 있다.
## 질문 내용
```java
 public static <E extends Comparable<? super E>> E max(List<? extends E> list) {
        if (list.isEmpty()) {
            throw new IllegalArgumentException("컬렉션이 비어 있습니다.");
        }

        E result = null;
        for (E e : list) {
            if (result == null || e.compareTo(result) > 0) {
                result = Objects.requireNonNull(e);
            }
        }

        return result;
    }
```
위의 함수를 사용하면 Comparable<ScheduleFuture>의 구현 없이도 List<ScheduleFuture<?>>이 사용가능한데, 그 이유가 Comparable<E>의 하위 타입 중에 ScheduleFuture이 있어서 그런 것인지 감은 오는데 정확히 이해가 안간다.

**Comment by seonjuleee** [comment]
ScheduleFuture 인터페이스는 다음과 같은 상속 형태를 띄기 때문에, ScheduledFuture는 상위 인터페이스인 Delayed와도 비교가 가능해진다.
![110250253-ae9cf300-7fbd-11eb-87cd-0d1255eab281](https://user-images.githubusercontent.com/52817735/166132707-967b51d3-8506-4a32-9d24-36d38f9a6905.png)
그런데 수정 전 max는 자기 자신과 비교 가능한 것을 지원하기 때문에, ScheduledFuture 리스트를 거부하게 된다.
그렇기 때문에 직접 구현한 다른 타입을 확장한 타입을 지원하려면 와일드카드가 필요해진다.
