### ISSUE TITLE
[item31] 비한정적 타입 매개변수와 비한정적 타입 와일드 카드의 차이

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#62]
> 188 pg, public API라면 간단한 두 번째가 낫다. 어떤 리스트든 이 메서드에 넘기면 명시한 인덱스의 원소들을 교환해 줄 것이다. 신경써야 할 타입 매개변수도 없다. 
> 189 pg, public API로 쓰기에는 너무 복잡하다.
## 질문 내용
매개변수가 하나인 함수에서 비한정적 타입 매개변수를 사용한 함수보다 비한정적 와일드 카드를 사용한 함수가 왜 더 좋은지 잘 모르겠음.
비한정적 타입 매개변수를 사용한 함수가 public API로 쓰기에는 복잡한 것인지 이해가 잘 안감

**Comment by seonjuleee** [comment]
public API인 경우, 그리고 매개변수가 한 개인 경우에는, 비한정적 타입 매개변수와 비한정적 와일드카드 모두 사용이 가능해진다. 
그런데 앞서 타입 매개변수 보다는 와일드카드를 사용하는 것이 유연성을 더 높인다고 하였고, 코드도 더 간단해지기 때문에 와일드카드를 추천하는 것이다.
