### ISSUE TITLE
[item32] 힙 오염

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#63]
> 191 pg, 매개변수화 타입의 변수가 타입이 다른 객체를 참조하면 힙 오염이 발생한다.
## 질문 내용
힙 오염이 정확히 어떤 내용인지 모르겠음

**Comment by seonjuleee** [comment]
힙 오염은 메모리 공간인 힙에 문제가 생기는 것이다.
힙 오염의 대표적인 원인 중 하나가 힙 공간에 원래 있던 타입과 다른 타입이 저장되는 것이다.
