### ISSUE TITLE
[item 33] 한정적 타입 토큰의 예시

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#65]
> 204pg, 여기서 annotationType 인수는 애너테이션 타입을 뜻하는 한저적 타입 토큰이다.
## 질문 내용

```java
public <T extends Annotation> T getAnnotation(Class<T> annotationType);
```
여기에 있는 annotationType과 

```java
public <T> T getFavorite(Class<T> type) {
    return type.cast(favorites.get(type));
}
```
여기에 있는 type은 다른게 맞는 것인지? 아니면 annotationType은 한정적 타입 토큰이라고 했는데 type도 마찬가지로 한정적 타입 토큰인지 궁금하다.

**Comment by ehBeak** [comment]
첫번째 함수의 매개변수인 annotationType은 Class<T>의 T가 한정적 타입 토큰을 사용했기 때문에 Annotation에 한정된 것만 사용 가능하다.
반면에 두번째 함수의 매개변수는 Class<T>의 T에 한정적 타입 토큰을 사용하지 않았기 때문에 무엇이든 가능하다.
