### ISSUE TITLE
[item 34] int 상수 대신 열거 타입을 사용하라

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#66]
> 208pg, 하지만 열거 타입 상수는 생성자에서 자신의 인스턴스를 맵에 추가할 수 없다. 이렇게 하려면 컴파일 오류가 나는데, 약간 이 방식이 허용되었다면 런타임에 NullPointerException이 발생했을 것이다. 
## 질문 내용
생성자에서 자신의 인스턴스를 맵에 추가 한다는 의미가 무엇인지 모르겠다. 열거 타입에서도 생성자를 사용하는 예시가 궁금하다.

**Comment by seonjuleee** [comment]
```java
private static final Map<String, Operation3> stringToEnum =
        Stream.of(values()).collect(
                toMap(Object::toString, e -> e)
        );

public static Optional<Operation3> fromString(String symbol) {
    return Optional.ofNullable(stringToEnum.get(symbol));
}
```
열거 타입을 사용할 때 toString에서 반환되는 값을 열거타입 상수로 변환하기 위해 `fromString` 메서드를 구현하는 예시를 보면, `stringToEnum`에서 스트림을 이용해서 Map을 반환한다.

이때 스트림을 사용하지 않을 경우에는 빈 해시맵을 만든 후 values가 반환한 배열을 순회하며 {문자열, 열거 타입 상수} 쌍을 맵에 추가해야한다.
그런데, 열거 타입의 경우 생성자에서는 자신의 인스턴스를 접근할 수 없고 상수 변수만 접근 가능하다. 
그래서 자신의 인스턴스를 맵에 추가할 수 없기 때문에 NullPointerException이 발생하게 될 것이다.
