### ISSUE TITLE
[item 3] 필드를 일시적(transient)라고 선언하는 법

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#67]
> 24pg, 모든 인스턴스를 일시적이라고 선언하고~
## 질문 내용
필드를 일시적이라고 선언하는 것에
대한 예시, transient의 역할이 궁금함

**Comment by seonjuleee** [comment]
transient는 Serialize하는 과정에 제외하고 싶은 경우 선언하는 키워드로 다음과 같이 사용된다.

```java
class Member implements Serializable {
    private transient String name;
    private String email;
    private int age;
}
```
이렇게 `transient`를 선언하면, Serializable을 할 때 `name`의 값은 `null`이 들어간다.
