### ISSUE TITLE
[item37]  EnumMap 생성자가 받는 키 타입의 Class 객체

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#69]
> 228pg, EnumMap의 생성자가 받는 키 타입의 Class 객체는 한정적 타입 토큰으로, 런타임 제네릭 타입 정보를 제공한다.
## 질문 내용
위 문장이 이해가 안감
EnumMap 생성자가 받는 Plant.LifeCycle.Class가 무엇을 의미하는지 모르겠음.
Class 객체에 대해서 잘 모르겠음.

**Comment by seonjuleee** [comment]
Classs 객체는 클래스 타입이 무엇인지를 알려주는 것
EnumMap의 생성자는 타입을 매개변수로 받아서 키에 해당하는 타입을 저장한다.
