### ISSUE TITLE
[item5] 의존 객체 주입과 의존성(의존관계)주입(DI)의 차이점

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#7]
> pg.29
## 질문 내용
생성자를 통한 의존 객체 주입과 의존 관계 주입(DI)의 차이점

**Comment by seonjuleee** [comment]
의존 객체 주입은 객체에 객체를 주입 받아 의존성을 나타내는 방식이라면, 의존 관계 주입은 객체에 인터페이스를 주입해 의존성을 나타내는 것이다.
객체가 아닌 인터페이스를 주입하는 이유는 결합도를 낮춰 유연하게 사용할 수 있기 때문이다.
