### ISSUE TITLE
[item 37] 코드 37-6의 동작 방식

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#70]
> 230 pg, 두 번째 수집기인 toMap에서는 이후 상태를 전이에 대응시키는 EnumMap을 생성한다.
## 질문 내용
코드 37-6 중
` private static final Map<Phase, Map<Phase, Transition>> m ` 을 초기화 하는 과정에서 groupingBy()와 toMap()의 동작방식을 잘 모르겠음

**Comment by seonjuleee** [comment]
```java
private static final Map<Phase, Map<Phase, Transition>> m =
      Stream.of(values()) // (1)
      .collect(Collectors.groupingBy(t -> t.from, () -> new EnumMap<>(Phase.class),  // (2)
              Collectors.toMap(t -> t.to, t -> t, (x, y) -> y, () -> new EnumMap<>(Phase.class)) // (3)
      ));
```

(1) 먼저 `values()`로 Transition들을 꺼낸다
(2) from 값이 같은 것들을 모아 EnumMap으로 만들어 반환
(3) to값이 같은 것들을 EnumMap으로 만들어 반환
하여 Map<Phase, Map<Phase, Transition>>을 반환하는 메서드이다.
