### ISSUE TITLE
[item 38] 아무 상태에 의존하지 않을 때, 열거 타입 끼리 구현을 상속하는 법

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#72]
> 235 pg, 바로 열거 타입끼리 구현을 상속할 수 없다는 점이다. 아무 상태에도 의존하지 않는 경우에는 디폴트 구현을 이용해 인터페이스에 추가하는 방법이 있다.
## 질문 내용
위 문장의 예시가 궁금함

**Comment by seonjuleee** [comment]
의존하지 않는 열거타입의 경우, 디폴트 구현을 인터페이스에 추가하면 열거 타입끼리도 구현을 상속한 것과 같은 효과를 낼 수 있다는 의미이다.
