### ISSUE TITLE
[item 5] 불변을 보장하면 여러 클라이언트가 의존객체를 안심하고 공유할 수 있는 이유

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#74]
> 29pg, 또한 불변을 보장하여 (같은 자원을 사용하려는) 여러 클라이언트가 의존 객체들을 안심하고 공유할 수 있기도 하다.
## 질문 내용
불변을 보장하는 경우 왜 의존객체들을 안전하게 공유할 수 있는지 잘 모르겠음

**Comment by seonjuleee** [comment]
의존 객체가 불변인 경우 값이 변하지 않으므로 이를 사용하는 클라이언트가 의존객체가 변하지 않는 것에 안심하고 공유할 수 있다는 뜻이다.
