### ISSUE TITLE
[item 39] 프로그램 요소를 매개변수로 전달하는 방법

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#75]
> 237pg, 예외의 이름을 테스트 메서드 이름에 덧붙이는 방법도 있지만, 보기에 나쁘고 깨지기도 쉽다.
## 질문 내용
프로그램 요소를 매개변수로 전달할 방법중에 예외의 이름을 테스트 메소드 이름에 덧붙이는 방법이 무엇을 말하는지 잘 모르겠음

**Comment by seonjuleee** [comment]
http://javaprepare.blogspot.com/2008/06/junit-3.html
If you want to test a method that will throw an exception under a specific condition, you can:

Put the test code inside a "try" block".
Catch the expected exception object.
Assert the exception object with Assert.assertNotNull().

try 문을 사용해서 catch로 예외를 잡고, 예외 처리를 `Assert.assertNotNull();`로 하면 된다.
