### ISSUE TITLE
[item39] isAnnotationPresent가 반복 가능 애너테이션을 검사할 수 없는 이유

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#77]
> 244pg, 따라서 반복 가능 애너테이션을 여러 번 단 다음 isAnnotationPresent로 반복 가능 애너테이션이 달렸는지 검사한다면 "그렇지 않다"라고 알려준다.(컨테이너가 달렸기 때문이다)
## 질문 내용
컨테이너 여부와 isAnnotationPresent가 반복가능 애너테이션이 달렸는지 검사할 수 없는 이유의 관계를 모르겠다.

**Comment by seonjuleee** [comment]
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@Repeatable(ExceptionTestContainer.class)
public @interface ExceptionRepeatTest {
    // <? extends Throwable> : Throwable을 확장한 클래스의 Class 객체 -> 모든 예외와 오류 타입 다 수용
    Class<? extends Throwable> value();
}
```
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ExceptionTestContainer {
    ExceptionRepeatTest[] value();
}
```

이 둘의 `value()` 메서드를 보면, 반복 가능 애너테이션을 정의한 `ExceptionRepeatTest`에서는 예외 클래스 하나만 반환하고,
컨테이너 애너테이션을 정의한 `ExceptionTestContainer`는 예외 클래스 배열을 반환하므로,

`isAnnotationPresent(ExceptionRepeatTest.class);`를 하면 여러번 단 메서드만 검사하고,
`isAnnotationPresent(ExceptionTestContainer.class);`를 하면 여러번 단 메서드만 검사하게 된다.

따라서 달려있는 애너테이션 수와 상관없이 모두 검사하기 위해서는 둘을 따로따로 확인해야하는 것이다.
