### ISSUE TITLE
[item41] 마킹이 된 객체를 매개변수로 받을 때

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#78]
> 250pg, 마커를 클래스나 인터페이스에 적용해야 면 ~라고 자문해보자. 답이 "그렇다"이면 마커 인터페이스를 써야한다. 이렇게 하면 그 마커 인터페이스를 해당 메서드의 매개변수 타입으로 사용하여 컴파일 타임에 오류를 잡아낼 수 있다.
## 질문 내용
컴파일 타임에 어떤 오류를 잡아낼 수 있다는 것인지 잘 모르겠다.
마커 클래스나 인터페이스를 매개변수로 사용한 예시

**Comment by seonjuleee** [comment]
마킹이 된 객체를 매개변수로 받는 메서드를 작성하는 일이 있으면 마커 인터페이스를 사용하는 것이기 때문에, 해당 메서드의 매개변수 타입으로 잘못된 객체를 넣었을 시 컴파일 오류가 발생하는 것이다.
