### ISSUE TITLE
[item 41] 마커 인터페이스를 사용할 경우 컴파일 타임에 잡는 오류

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#79]
> 249pg, 마커 인터페이스는 어엿한 타입이기 때문에, 마커 애너테이션을 사용했다면 런타임에야 발견된 오류를 컴파일 타임에 잡을 수 있다. ~ 마커 인터페이스를 사용하는 주요 이류가 컴파일 타임 오류 검출인데, 그 이점을 살리지 못한 것이다.
## 질문 내용
위의 예시가 궁금함. 
Serializable을 매개변수를 받는 방법이 궁금함.

**Comment by seonjuleee** [comment]
```java
if (obj instanceof Serializable) {
    writeOrdinaryObject(obj, desc, unshared);
}
```

이런식으로 `obj instanceof Serializable`을 통해 직렬화가 가능한지를 확인할 수 있다.
