### ISSUE TITLE
[item 39] 반복 가능 애너테이션이 달려있는 메서드와 컨테이너 애너테이션을 따로 확인해야하는 이유

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#80]
> 244pg, 따라서 반복 가능 애너테이션을 여러 번 단 다음 isAnnotationPresent로 반복 가능 애너테이션이 달렸는지 검사한다면 "그렇지 않다"라고 알려준다. ~ 그래서 달려 있는 수와 상관없이 모두 검사하려면 둘을 따로따로 확인해야 한다.
## 질문 내용
왜 "그렇지 않다"로 나오는지 제대로 이해를 하지 못했고, 코드 39-10에 있는 내용의 설명이 조금 더 필요하다.

**Comment by ehBeak** [comment]
먼저 ExceptionTest 어노테이션의 선언부를 보면, 다음과 같다.
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@Repeatable(ExceptionTestContainer.class)
public @interface ExceptionTest {
    Class<? extends Throwable> value();
}
```
value의 반환타입은 Class<? extends Throwable> 하나이다.


컨테이너인 ExceptionTestContainer 어노테이션의 선언부를 보면 다음과 같다.
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface TestContainer {
    Test[] value();
}
```
vlaue의 반환타입은 Test[]로 배열이다.

때문에 isPresentAnnotation함수를 쓸 때, @ExceptioinTest는 값이 하나만 반환되는 것이고 @ExceptionTestContainer는 Test배열이 반환된다. 그래서 각각 구분해서 isPresentAnnotation을 사용해야한다.
