### ISSUE TITLE
[item 42] 비교자 생성 메서드

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#86]
> 255pg, 람다 자리에 비교 생성 메서드를 사용하면 이 코드를 더 간결하게 만들 수 있다.
## 질문 내용
비교 생성 메서드가 무엇이고 어떻게 사용하는 것인지 모르겠다.

**Comment by seonjuleee** [comment]
```java
Collections.sort(words, Comparator.comparingInt(String::length));
```
`comparingInt()` 메서드는 비교자를 받아 비교할 수 있도록 하는 메서드인데, String 타입의 length로 비교하는 것이기 때문에 위와 같이 표현이 된 것이다.
