### ISSUE TITLE
[item 8] 객체 생성을 막는 방법

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#89]
> pg, 42 객체 생성을 막으려면 예외를 던지는 것만으로 충분하지만, finalizer가 있다면 그렇지도 않다.
## 질문 내용
예시가 궁금함, finalizer을 어떻게 사용하는 것인지 궁금하다.

**Comment by seonjuleee** [comment]
finalizer()는 객체를 생성할 때 취약점이 존재한다. 
```java
public class Zombie {
	static Zombie zombie;

	public void finalize() {
		zombie = this;
	}
}
```
이런 식으로 작성되면 객체를 참조해제 하더라도 다시 참조가 되어 객체가 계속 살아있게 된다.
