### ISSUE TITLE
[item5] 한정적 와일드카드 타입이란?

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#9]
> 29pg, Supplier<T>를 입력으로 받는 메서드는 일반적으로 한정적 와일드카드 타입을 사용해 팩터리의 타입 매개변수를 제한해야 한다.

**Comment by ehBeak** [comment]
한정적 와일드 카드란 타입의 제한을 풀어줄 때 사용한다.

1. Upper Bounded Wildcards
`List<? extends T> list; // T타입의 자식클래스들을 허용한다.`

2. Lower Bounded Wildcards
`List<? super T> list; // T타입의 부모 클래스들을 허용한다.`

3. 
`List<?> list; // 모든 타입을 허용한다`
