### ISSUE TITLE
[item44] 함수 인터페이스 사용법

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/Effective-Java-Study#93]
> pg,264 앞의 LinkedHashMap 예에서는 직접 만든 EldestEntryRemovalFunction 대신 표준 인터페이스인 BiPredicate<Map<K,V>, Map.Entry<K,V>>를 사용할 수 있다.
## 질문 내용
함수 인터페이스를 선언하는 방법은 알겠는데, 어떻게 사용, 적용하는지 모르겠다(클라이언트 입장?에서)

**Comment by seonjuleee** [comment]
다른 메서드처럼 동일하게 사용하면 된다.
