### ISSUE TITLE
[item 44] 람다를 사용함으로써 템플릿 메서드 패턴의 매력이 줄은 이유와 해결 방법

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#94]
> 263pg, 예컨대 상위 클래스의 기본 메서드를 재정의해 원하는 동작을 구현하는 템플릿 메서드 패턴의 매력이 크게 줄었다. 이를 대체하는 현대적인 해법은 같은 효과의 함수 객체를 받는 정적 팩터리나 생성자를 제공하는 것이다. 이 내용을 일반화해서 말하면 함수 객체를 매개변수로 받는 생성자와 메서드를 더 많이 만들어야 한다.
## 질문 내용
람다를 사용함으로써 템플릿 메서드 패턴의 매력이 줄어 이를 대체하려면 함수 객체를 매개변수로 받는 생성자와 메서드를 많이 만들어야 한다는데, 이 흐름이 잘 이해가 가지 않는다.

**Comment by ehBeak** [comment]
템플릿 메서드를 사용하면 오버라이딩을 사용한다. 때문에 선언되어있는 인스턴스 객체의 인스턴스 함수를 바로 사용할 수 있다. 이런 이유로 함수 객체를 매개변수로 받을 필요가 없다.
하지만 람다를 사용하면 인스턴스 함수를 바로 사용할 수 없기 때문에 함수 객체를 매개변수로 받는 생성자와 메서드를 많이 만들어야한다.
