### ISSUE TITLE
[item 44] Map이 자기 자신도 함수 객체에 건네줘야 하는 이유

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#95]
> 263pg, 하지만 생성자에 넘기는 함수 객체는 이 맵의 인스턴스 메서드가 아니다. 팩터리나 생성자를 호출할 때는 맵의 인스턴스가 존재하지 않기 때문이다. 따라서 맵은 자기 자신도 함수 객체에 건네줘야 한다. 
## 질문 내용
팩터리나 생성자를 호출할 때 맵의 인스턴스가 존재하지 않는 이유가 궁금하다.

**Comment by ehBeak** [comment]
템플릿 메서드 패턴을 사용할 때는 인스턴스 메서드를 바로 사용할 수 있지만 팩터리나 생성자를 호출할 때는 객체가 생성되어 있지 않을 수 있다. 때문에 바로 인스턴스 함수에 접근하는 것은 위험하다. 그렇기 때문에 자기 자신도 함수 객체의 매개변수로 넘겨줘야 한다.
