### ISSUE TITLE
[item 45] 스트림 사용하기 어려운 예시

### ISSUE THREAD

**Issue by seonjuleee** [ehBeak/Effective-Java-Study#96]
> 275pg, 하지만 다행히 첫 번째 중간 연산에서 수행한 매핑을 거꾸로 수행해 메르센 수의 지수를 쉽게 계산해낼 수 있다.
## 질문 내용
스트림을 사용해 메르센 소수의 지수를 출력해야 하는 예제에서 `첫번째 중간 연산에서 수행한 매핑을 거꾸로 수행`한다는 부분이 어떻게 되는 것인지 이해가 잘 가지 않는다.

**Comment by ehBeak** [comment]
스트림의 한 특징으로, 이미 중간 연산이 수행되면 원본 데이터는 변경이 된다. 때문에 메르센 지수를 출력하는 코드에서도 중간 연산이 수행되면 원본이 변경된다.
문제는 소수의 지수를 출력하려면 원본 또한 알아야하는데 이미 중간 연산으로 변경되어서 원본을 다시 복원해야한다. 그 과정을 위해 수행한 매핑을 거꾸로 수행한다는 것이다.
